import js from '@eslint/js';
import expoConfig from 'eslint-config-expo/flat.js';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig([
  globalIgnores([
    '**/node_modules/',
    '**/.expo/',
    '**/dist/',
    'apps/mobile/android/',
    'apps/mobile/ios/',
    'supabase/.temp/',
    // Generated by `pnpm gen:types`.
    'supabase/functions/_shared/pure/database.ts',
  ]),

  // Everything outside the mobile app: scripts, shared pure code, root configs.
  {
    files: ['**/*.{ts,mts,js,mjs}'],
    ignores: ['apps/mobile/**'],
    extends: [js.configs.recommended, tseslint.configs.strict],
    languageOptions: { globals: globals.node },
  },

  // Mobile app: Expo's React Native rules, scoped to apps/mobile.
  {
    basePath: 'apps/mobile',
    extends: [expoConfig],
    settings: {
      // Resolve tsconfig `paths` (`@/*`, `@shared/*`).
      'import/resolver': {
        typescript: { project: `${import.meta.dirname}/apps/mobile/tsconfig.json` },
      },
    },
  },
  {
    basePath: 'apps/mobile',
    files: ['*.config.js'],
    languageOptions: { globals: globals.node, sourceType: 'commonjs' },
  },

  // Shared by all TypeScript.
  {
    files: ['**/*.{ts,tsx,mts}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },

  // pure/ runs in both Deno and React Native: no runtime-specific globals or external imports.
  {
    files: ['supabase/functions/_shared/pure/**/*.ts'],
    languageOptions: { globals: {} },
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'Deno', message: 'pure/ cannot use Deno APIs.' },
        { name: 'process', message: 'pure/ cannot use Node APIs.' },
        { name: 'window', message: 'pure/ cannot use DOM APIs.' },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              // Catches bare packages as well as npm:, jsr:, node: and URL specifiers.
              regex: '^[^./]',
              message: 'pure/ must stay dependency-free: only relative imports.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['supabase/functions/_shared/pure/**/*.test.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  // Maestro runScript files: Maestro's JavaScript globals, and each runScript env key as a global.
  {
    files: ['e2e/maestro/scripts/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        http: 'readonly',
        json: 'readonly',
        output: 'writable',
        ACTION: 'readonly',
        BODY: 'readonly',
        BOT_PORT: 'readonly',
        EXPECT_DM: 'readonly',
      },
    },
  },
]);
