// The seed file built from content/*.json, and its name.
//
// The Supabase CLI runs a seed file once per path: `db push --include-seed` on a path it has
// already seeded only records the new hash and skips the SQL. So the output gets a new name
// whenever its content changes: supabase/seeds/content-<id>.sql, with config.toml seeding
// ./seeds/*.sql. The id chains the previous file's name into the hash, so returning to an earlier
// content (A → B → A) still gets a name the hosted project has not seen.
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  parseAliasWords,
  parseCampusVenues,
  parseProfanity,
  parseHarfCategories,
  parseSahtekarWords,
  parseSarkiWords,
  parseSohbetCards,
  parseTabuCards,
  parseTestVenues,
  parseVenuesFile,
} from './content.ts';
import {
  aliasWordsSql,
  campusSql,
  cardsSql,
  profanitySql,
  testSpotsSql,
  venuesSql,
} from './sections.ts';

export const SEEDS_DIR = 'supabase/seeds';
const SEED_FILE = /^content-[0-9a-f]{12}\.sql$/;

export type SeedFile = { name: string; sql: string };

export function isSeedFileName(name: string): boolean {
  return SEED_FILE.test(name);
}

// Keeps the existing name while the content is the same; otherwise a new name chained from the
// files it replaces (sorted, so the result does not depend on directory order).
export function seedFileName(sql: string, existing: readonly SeedFile[]): string {
  const [only] = existing;
  if (existing.length === 1 && only?.sql === sql) return only.name;
  const previous = existing
    .map((f) => f.name)
    .sort()
    .join('\n');
  const id = createHash('sha256').update(`${previous}\n${sql}`).digest('hex').slice(0, 12);
  return `content-${id}.sql`;
}

export type SeedBuild = { sql: string; venues: number; testVenues: number; campusVenues: number };

export function buildSeed(root: string): SeedBuild {
  const readJson = (path: string): unknown => JSON.parse(readFileSync(resolve(root, path), 'utf8'));

  // venues-pilot.json is produced by `pnpm fetch:venues` and may not exist yet.
  const venuesPath = 'content/venues-pilot.json';
  const venues = existsSync(resolve(root, venuesPath))
    ? parseVenuesFile(readJson(venuesPath)).venues
    : [];

  // venues-test.json holds hand-entered field test venues; skipped when missing or empty.
  const testVenuesPath = 'content/venues-test.json';
  const testVenues = existsSync(resolve(root, testVenuesPath))
    ? parseTestVenues(readJson(testVenuesPath))
    : [];

  // venues-campus.json: venues with a boundary and spots (docs/SPEC_V3.md §4.1), validated here.
  const campusPath = 'content/venues-campus.json';
  const campus = existsSync(resolve(root, campusPath))
    ? parseCampusVenues(readJson(campusPath))
    : [];

  const profanity = parseProfanity(readJson('content/profanity-tr.json'));

  const sections = [
    aliasWordsSql(parseAliasWords(readJson('content/aliases-tr.json'))),
    venuesSql(venues),
    ...(testVenues.length > 0 ? [venuesSql(testVenues, testVenuesPath, null)] : []),
    ...testSpotsSql(testVenues),
    campusSql(campus),
    profanitySql(profanity),
    cardsSql(
      parseTabuCards(readJson('content/tabu-cards.json')),
      parseSohbetCards(readJson('content/sohbet-cards.json')),
      parseSahtekarWords(readJson('content/sahtekar-words.json'), profanity),
      parseHarfCategories(readJson('content/harf-categories.json'), profanity),
      parseSarkiWords(readJson('content/sarki-words.json'), profanity),
    ),
  ];

  const header = '-- Generated by scripts/build-seed.ts from content/. Do not edit by hand.\n';
  return {
    sql: [header, ...sections].join('\n'),
    venues: venues.length,
    testVenues: testVenues.length,
    campusVenues: campus.length,
  };
}
