// Builds supabase/seed.sql from content/*.json. The output is committed.
// Each milestone that introduces content adds its section generator here.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = resolve(root, 'supabase/seed.sql');

const sections: string[] = [];

const header = '-- Generated by scripts/build-seed.ts from content/. Do not edit by hand.\n';
writeFileSync(outFile, [header, ...sections].join('\n'));
console.log(`Wrote ${outFile} (${sections.length} sections)`);
