// Builds supabase/seed.sql from content/*.json. The output is committed.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseAliasWords, parseVenuesFile } from './seed/content.ts';
import { aliasWordsSql, venuesSql } from './seed/sections.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = resolve(root, 'supabase/seed.sql');

function readJson(path: string): unknown {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8'));
}

// venues-pilot.json is produced by `pnpm fetch:venues` and may not exist yet.
const venuesPath = 'content/venues-pilot.json';
const venues = existsSync(resolve(root, venuesPath))
  ? parseVenuesFile(readJson(venuesPath)).venues
  : [];

const sections = [
  aliasWordsSql(parseAliasWords(readJson('content/aliases-tr.json'))),
  venuesSql(venues),
];

const header = '-- Generated by scripts/build-seed.ts from content/. Do not edit by hand.\n';
writeFileSync(outFile, [header, ...sections].join('\n'));
console.log(`Wrote ${outFile} (${venues.length} venues)`);
