// Builds supabase/seed.sql from content/*.json. The output is committed.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  parseAliasWords,
  parseCampusVenues,
  parseProfanity,
  parseSohbetCards,
  parseTabuCards,
  parseTestVenues,
  parseVenuesFile,
} from './seed/content.ts';
import { aliasWordsSql, campusSql, cardsSql, profanitySql, venuesSql } from './seed/sections.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = resolve(root, 'supabase/seed.sql');

function readJson(path: string): unknown {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8'));
}

// venues-pilot.json is produced by `pnpm fetch:venues` and may not exist yet.
const venuesPath = 'content/venues-pilot.json';
const venues = existsSync(resolve(root, venuesPath))
  ? parseVenuesFile(readJson(venuesPath)).venues
  : [];

// venues-test.json holds hand-entered field test venues; skipped when missing or empty.
const testVenuesPath = 'content/venues-test.json';
const testVenues = existsSync(resolve(root, testVenuesPath))
  ? parseTestVenues(readJson(testVenuesPath))
  : [];

// venues-campus.json: venues with a boundary and spots (docs/SPEC_V3.md §4.1), validated here.
const campusPath = 'content/venues-campus.json';
const campus = existsSync(resolve(root, campusPath)) ? parseCampusVenues(readJson(campusPath)) : [];

const sections = [
  aliasWordsSql(parseAliasWords(readJson('content/aliases-tr.json'))),
  venuesSql(venues),
  ...(testVenues.length > 0 ? [venuesSql(testVenues, testVenuesPath, null)] : []),
  campusSql(campus),
  profanitySql(parseProfanity(readJson('content/profanity-tr.json'))),
  cardsSql(
    parseTabuCards(readJson('content/tabu-cards.json')),
    parseSohbetCards(readJson('content/sohbet-cards.json')),
  ),
];

const header = '-- Generated by scripts/build-seed.ts from content/. Do not edit by hand.\n';
writeFileSync(outFile, [header, ...sections].join('\n'));
console.log(
  `Wrote ${outFile} (${venues.length} venues, ${testVenues.length} test venues, ${campus.length} campus venues)`,
);
