import { baseTypography, type ThemeDefinition } from './tokens';

// The app's one theme, "Oyun Gecesi": cream ground, ink outlines, a purple accent, lemon and orange
// stickers, hard ink shadows; Bricolage Grotesque 800 headings over Nunito. Visual source: the
// Claude Design canvas (Aşama 1 · Son → Palet, Tipografi, Bileşenler). Every text/ground pair is
// AA (contrast.test.ts). Trust surfaces (sheets, `Quiet`) drop the outlines and hard shadows.
export const THEME: ThemeDefinition = {
  defaultScheme: 'system',
  palettes: {
    light: {
      canvas: '#FFF7E6',
      surface: '#FFFFFF',
      surface2: '#FFF0CC',
      text: '#1B1433',
      muted: '#544A6B',
      accent: '#5B2EEA',
      onAccent: '#FFFFFF',
      border: '#1B1433',
      divider: '#DDD5EA',
      danger: '#C42B14',
      onDanger: '#FFFFFF',
      success: '#1F7A3A',
      onSuccess: '#FFFFFF',
      signal: '#E6F3A6',
      onSignal: '#1B1433',
      calm: '#E4F4FF',
      onCalm: '#0F4A73',
      lively: '#FFE3F1',
      onLively: '#8A1454',
      buzz: '#D7F75B',
      onBuzz: '#1B1433',
      event: '#FF6B3D',
      onEvent: '#1B1433',
      scrim: '#000000',
    },
    dark: {
      canvas: '#140E26',
      surface: '#211842',
      surface2: '#2C2156',
      text: '#FBF7FF',
      muted: '#C6BAE6',
      accent: '#A98BFF',
      onAccent: '#140E26',
      border: '#FBF7FF',
      divider: '#3E3470',
      danger: '#FF8B75',
      onDanger: '#1E0903',
      success: '#7FE08F',
      onSuccess: '#07210E',
      signal: '#C9DE7A',
      onSignal: '#140E26',
      calm: '#1D3A57',
      onCalm: '#CDEBFF',
      lively: '#4E1B3C',
      onLively: '#FFD1EA',
      buzz: '#D7F75B',
      onBuzz: '#140E26',
      event: '#FF7A50',
      onEvent: '#140E26',
      scrim: '#000000',
    },
  },
  fonts: {
    display: 'BricolageGrotesque_800ExtraBold',
    displayItalic: null,
    italic: null,
    regular: 'Nunito_400Regular',
    semibold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
    extrabold: 'Nunito_800ExtraBold',
  },
  shape: {
    radius: { sm: 12, md: 18, lg: 24, pill: 999 },
    stroke: { card: 2, control: 2, tag: 2, hairline: 1, venueRing: 2 },
    shadow: {
      card: '3px 3px 0px {border}',
      primaryButton: '3px 3px 0px {border}',
      button: '3px 3px 0px {border}',
      venueButton: null,
      raised: '3px 3px 0px {border}',
      pin: '0px 4px 10px rgba(0, 0, 0, 0.25)',
      // The floating tab bar: wide, soft, low opacity (no outline on its top edge).
      tabBar: '0px 14px 36px -8px rgba(0, 0, 0, 0.24)',
      focus: '3px 3px 0px {accent}',
    },
    selectedTeam: 'fill',
    screenPadding: 20,
  },
  typography: baseTypography({
    display: { font: 'display', size: 30, lineHeight: 34, letterSpacing: -0.6 },
    word: { font: 'display', size: 40, lineHeight: 44, letterSpacing: -0.8 },
  }),
  eventTagTilt: -2,
  profiledTagDashed: false,
};
