import { baseTypography, type ThemeDefinition } from '../tokens';

// Sakin Liman: hairlines, space, one quiet accent.
export const calm: ThemeDefinition = {
  name: 'calm',
  defaultScheme: 'system',
  palettes: {
    light: {
      canvas: '#F5F8F7',
      surface: '#FFFFFF',
      surface2: '#EBF2F0',
      text: '#13211E',
      muted: '#4B5D59',
      accent: '#1C6B62',
      onAccent: '#FFFFFF',
      border: '#D9E3E0',
      divider: '#D9E3E0',
      danger: '#A8261C',
      onDanger: '#FFFFFF',
      success: '#1F6B3F',
      onSuccess: '#FFFFFF',
      signal: '#1E7268',
      onSignal: '#FFFFFF',
      calm: '#E8EFED',
      onCalm: '#3C4E4A',
      lively: '#E0F0EC',
      onLively: '#185E55',
      buzz: '#FDF0DC',
      onBuzz: '#7A4A0A',
      event: '#EEF0FB',
      onEvent: '#34407A',
      scrim: '#000000',
    },
    dark: {
      canvas: '#0E1614',
      surface: '#15201D',
      surface2: '#1C2926',
      text: '#E7F0ED',
      muted: '#A2B4AF',
      accent: '#7DD0C2',
      onAccent: '#08201C',
      border: '#27352F',
      divider: '#27352F',
      danger: '#FF8F84',
      onDanger: '#2A0906',
      success: '#86D9A6',
      onSuccess: '#062212',
      signal: '#3FA596',
      onSignal: '#04110F',
      calm: '#223029',
      onCalm: '#C2D1CC',
      lively: '#133B35',
      onLively: '#A9ECDF',
      buzz: '#3D2E14',
      onBuzz: '#F6D39B',
      event: '#232A4A',
      onEvent: '#C9D1FF',
      scrim: '#000000',
    },
  },
  fonts: {
    display: 'Figtree_700Bold',
    displayItalic: null,
    italic: null,
    regular: 'Figtree_400Regular',
    semibold: 'Figtree_600SemiBold',
    bold: 'Figtree_700Bold',
    extrabold: 'Figtree_800ExtraBold',
  },
  shape: {
    radius: { sm: 8, md: 12, lg: 16, pill: 999 },
    stroke: { card: 1, control: 1, tag: 0, hairline: 1, venueRing: 4 },
    shadow: {
      card: null,
      primaryButton: null,
      button: null,
      venueButton: '0px 4px 12px -4px rgba(0, 0, 0, 0.3)',
      raised: '0px 1px 3px rgba(0, 0, 0, 0.15)',
      pin: '0px 4px 10px rgba(0, 0, 0, 0.18)',
    },
    selectedTeam: 'ring',
    screenPadding: 22,
  },
  typography: baseTypography({
    display: { font: 'display', size: 28, lineHeight: 32, letterSpacing: -0.4 },
    button: { font: 'semibold', size: 16, lineHeight: 20 },
    buttonLarge: { font: 'semibold', size: 18, lineHeight: 22 },
    tag: { font: 'semibold', size: 13, lineHeight: 17 },
  }),
  eventTagTilt: 0,
  profiledTagDashed: false,
};
